export const FlatNav = [
    {
      id: 100,
      icon: 'pe-7s-home',
      label: 'Home',
      to: '/',
      component: 'Home',
    },
    {
      id: 200,
      icon: 'pe-7s-users',
      label: 'User Management',
    },
    {
      id: 201,
      parentId: 200,
      icon: 'pe-7s-user',
      label: 'Manage User',
      to: '/users',
      component: 'User',
    },
    {
      id: 300,
      icon: 'pe-7s-users',
      label: 'Menu Management',
    },
    {
      id: 301,
      parentId: 300,
      icon: 'pe-7s-user',
      label: 'Menu',
      to: '/managemenu',
      component: 'ManageMenu',
    },
    {
      id: 302,
      parentId: 300,
      icon: 'pe-7s-user',
      label: 'Role',
      to: '/managerole',
      component: 'ManageRole',
    },
    {
      id: 303,
      parentId: 300,
      icon: 'pe-7s-user',
      label: 'Role Menu',
      to: '/rolemenu',
      component: 'RoleMenu',
    },
    {
      id: 350,
      icon: 'pe-7s-users',
      label: 'Division Management',
    },
    {
      id: 351,
      parentId: 350,
      icon: 'pe-7s-user',
      label: 'State',
      to: '/managestate',
      component: 'ManageState',
    },
    {
      id: 352,
      parentId: 350,
      icon: 'pe-7s-user',
      label: 'District',
      to: '/managedistrict',
      component: 'ManageDistrict',
    },
    {
      id: 353,
      parentId: 350,
      icon: 'pe-7s-user',
      label: 'Panchayat',
      to: '/managepanchayat',
      component: 'ManagePanchayat',
    },
    {
      id: 354,
      parentId: 350,
      icon: 'pe-7s-user',
      label: 'Muncipality',
      to: '/managemuncipality',
      component: 'ManageMuncipality',
    },
    {
      id: 355,
      parentId: 350,
      icon: 'pe-7s-user',
      label: 'Corporation',
      to: '/managecorporation',
      component: 'ManageCorporation',
    },
    {
      id: 356,
      parentId: 350,
      icon: 'pe-7s-user',
      label: 'Ward',
      to: '/manageward',
      component: 'ManageWard',
    },
    {
      id: 357,
      parentId: 350,
      icon: 'pe-7s-user',
      label: 'Sector',
      to: '/managesector',
      component: 'ManageSector',
    },
    {
      id: 400,
      icon: 'pe-7s-users',
      label: 'Category Management',
    },
    {
      id: 500,
      icon: 'pe-7s-user',
      label: 'Group Mangement',
    },
    {
      id: 501,
      parentId: 500,
      icon: 'pe-7s-user',
      label: 'Client',
      to: '/manageclient',
      component: 'ManageClient',
    },
    {
      id: 502,
      parentId: 500,
      icon: 'pe-7s-user',
      label: 'Organisation',
      to: '/manageorganisation',
      component: 'ManageOrganisation',
    },
    {
      id: 503,
      parentId: 500,
      icon: 'pe-7s-user',
      label: 'Group Lead',
      to: '/grouplead',
      component: 'GroupLead',
    },
  
  ];
  