/*
 *
 * Layout constants
 *
 */

 

// export const DEFAULT_ACTION = 'app/Layout/DEFAULT_ACTION';
export const SET_ENABLE_BACKGROUND_IMAGE = 'LAYOUT/SET_ENABLE_BACKGROUND_IMAGE';

export const SET_ENABLE_MOBILE_MENU = 'LAYOUT/SET_ENABLE_MOBILE_MENU';
export const SET_ENABLE_MOBILE_MENU_SMALL = 'LAYOUT/SET_ENABLE_MOBILE_MENU_SMALL';

export const SET_ENABLE_FIXED_HEADER = 'LAYOUT/SET_ENABLE_FIXED_HEADER';
export const SET_ENABLE_HEADER_SHADOW = 'LAYOUT/SET_ENABLE_HEADER_SHADOW';
export const SET_ENABLE_SIDEBAR_SHADOW = 'LAYOUT/SET_ENABLE_SIDEBAR_SHADOW';
export const SET_ENABLE_FIXED_SIDEBAR = 'LAYOUT/SET_ENABLE_FIXED_SIDEBAR';
export const SET_ENABLE_CLOSED_SIDEBAR = 'LAYOUT/SET_ENABLE_CLOSED_SIDEBAR';
export const SET_ENABLE_FIXED_FOOTER = 'LAYOUT/SET_ENABLE_FIXED_FOOTER';

export const SET_ENABLE_PAGETITLE_ICON = 'LAYOUT/SET_ENABLE_PAGETITLE_ICON';
export const SET_ENABLE_PAGETITLE_SUBHEADING = 'LAYOUT/SET_ENABLE_PAGETITLE_SUBHEADING';
export const SET_ENABLE_PAGE_TABS_ALT = 'LAYOUT/SET_ENABLE_PAGE_TABS_ALT';

export const SET_BACKGROUND_IMAGE = 'LAYOUT/SET_BACKGROUND_IMAGE';
export const SET_BACKGROUND_COLOR = 'LAYOUT/SET_BACKGROUND_COLOR';
export const SET_COLOR_SCHEME = 'LAYOUT/SET_COLOR_SCHEME';
export const SET_BACKGROUND_IMAGE_OPACITY = 'LAYOUT/SET_BACKGROUND_IMAGE_OPACITY';

export const SET_HEADER_BACKGROUND_COLOR = 'LAYOUT/SET_HEADER_BACKGROUND_COLOR';

